### ISSUE TITLE
dubbo 2.6.2 版本时,  会有数据丢失关报错

### ISSUE THREAD

**Issue by Anymous526** [dubbo/dubbo-php-framework#14]
PHP Notice:  Undefined offset: 1 in /opt/dubbo-php-framework/common/protocol/fsof/DubboParser.php on line 153
PHP Fatal error:  Uncaught Exception: provider occur error in /opt/dubbo-php-framework/common/protocol/fsof/DubboParser.php:159
Stack trace:
#0 /opt/dubbo-php-framework/consumer/fsof/FSOFProcessor.php(283): com\fenqile\fsof\common\protocol\fsof\DubboParser->parseResponseBody(Object(com\fenqile\fsof\common\protocol\fsof\DubboResponse))
#1 /opt/dubbo-php-framework/consumer/fsof/FSOFProcessor.php(146): com\fenqile\fsof\consumer\fsof\FSOFProcessor->recvDataFromProvider(Object(com\fenqile\fsof\consumer\client\FSOFClient4Linux), Object(com\fenqile\fsof\common\protocol\fsof\DubboRequest))
#2 /opt/dubbo-php-framework/consumer/proxy/Proxy.php(119): com\fenqile\fsof\consumer\fsof\FSOFProcessor->executeRequest(Object(com\fenqile\fsof\common\protocol\fsof\DubboRequest), Array, 3, '192.168.1.70:20...')
#3 /opt/dubbo-php-framework/demo/demo-consumer/server/Consumer.php(14): com\fenqile\fsof\consumer\proxy\Proxy->__call('invoke', Array)
#4 {main}
  thrown in /opt/dubbo-php-framework/common/protocol/fsof/DubboParser.php on line 159

**Comment by cjb21sj** [comment]
据我的经验，在 line 124，记录一下$dataArr的数据格式：
        $_data = substr($response->getFullData(), self::PACKAGE_HEDA_LEN);
        $response->setResponseBody($_data);
        $dataArr = array();
        if ($_data) {
            $dataArr = explode(PHP_EOL, $_data);
        }
       //此处  log 
如数据结构，不是这样的：
        [
           0 => 1 （或者 2）
           1 =>[接收到的返回数据]
           2 =>[]
        ]
需要修改传输的数据类型，比如不要传递object，使用string或者json串
个人经验，供参考

**Comment by Anymous526** [comment]
此问题已经解决.  需要 dubbo 的序列化使用 fastjson
